# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cache-and-install:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Dependencies
        run: npm install

      - name: Add env variables
        run: echo jwt=${{ secrets.JWT }} >> .env && echo cloudinary_cloud_name=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> .env && echo cloudinary_api_key=${{ secrets.CLOUDINARY_API_KEY }} >> .env && echo cloudinary_api_secret=${{ secrets.CLOUDINARY_API_SECRET }} >> .env && echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env && echo port=${{ secrets.PORT }} >> .env && echo AWS_SES_USER=${{ secrets.AWS_SES_USER }} >> .env && echo AWS_HOST=${{ secrets.AWS_HOST }} >> .env && echo AWS_SES_PASSWORD=${{ secrets.AWS_SES_PASSWORD }} >> .env

      - name: Install pm2
        run: npm i pm2 -g

      - name: Start Pm2
        run: pm2 restart dist/index.js --name "udaan"